name: Ci

on: push

jobs:
    linting:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                python-version: ['3.9', '3.10']

        steps:
            - name: code checkout
              uses: actions/checkout@v3

            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.version }}

            - name: Install flake8
              run: |
                  pip install flake8

            - name: Run flake8
              run: |
                  flake8 app.py